#ifdef USE_ENERGYLEAF

#define ENERGYLEAF_TOKEN_EXPIRED_CODE 401
#define ENERGYLEAF_ENDPOINT_DATA_RETRY 400
#define ENERGYLEAF_ENDPOINT_DATA_RETRY_MSG "Value too high"

enum ENERGYLEAF_ERROR {
    ERROR,
    NO_ERROR,
    TOKEN_EXPIRED,
    RET,
    IGNORE
};

#endif