name: Build for PR or push in main

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install PlatformIO Core
        run: |
            pip install wheel
            pip install --upgrade platformio

      - name: Run PlatformIO
        run: platformio run -e tasmota
