name: Build and Release

permissions:
  contents: write
  packages: write

on:
  push:
    tags:
      - v[0-9]+.*
      
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}

   build-esp-8266:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install PlatformIO Core
        run: |
            pip install wheel
            pip install --upgrade platformio
            
      - name: Run PlatformIO
        run: platformio run -e tasmota
        
      - name: Zip firmware
        run: | 
             mkdir -p ./release
             7z a ./release/esp8266-build.zip ./build_output/*
        
      - name: Upload c assets to release
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh release upload $GITHUB_REF_NAME release/esp8266-build.zip
