name: Build_firmware_master

on:
  workflow_dispatch:      # Start a workflow
  push:
    branches: master
    paths-ignore:
    - '.github/**'        # Ignore changes towards the .github directory
    - '**.md'             # Do no build if *.md files changes
    
permissions: write-all

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:


  base-images:
    runs-on: ubuntu-latest
    if: github.repository == 'pgenergy/smart-electricity-meter'
    continue-on-error: true
    strategy:
      matrix:
        variant:
          - tasmota
          - tasmota-4M
          - tasmota-minimal
          - tasmota-display
          - tasmota-ir
          - tasmota-knx
          - tasmota-lite
          - tasmota-sensors
          - tasmota-zbbridge
          - tasmota-zigbee
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install wheel
          pip install -U platformio
      - name: Run PlatformIO
        run: platformio run -e ${{ matrix.variant }}
      - name: Upload firmware artifacts
        uses: jason2866/upload-artifact@v2.0.3
        with:
          name: firmware
          path: ./build_output

  
  Release:
    needs: [base-images]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    - name: Download Tasmota firmwares
      uses: jason2866/download-artifact@v3.0.4
      with:
        name: firmware
        path: ./mv_firmware
    - name: Download safeboot firmwares
      uses: jason2866/download-artifact@v3.0.4
      with:
        name: firmware_safeboot
        path: ./mv_firmware
    - name: Display structure of downloaded files
      run: ls -R ./mv_firmware/
    - name: Zip all map.gz files in one file -> map_all.zip
      run: 7z a -mx=9 -tzip -xr'!.*' map_all.zip mv_firmware/map
    - name: Release
      uses: jason2866/action-gh-release@v1.2
      #if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ github.run_number }}
        files: |
          ./mv_firmware/firmware/*
          map_all.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
